# Conexion a Base de datos en desarrollo local
spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/wear_store?useSSL=false&serverTimezone=America/Buenos_Aires
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
cloud:
  aws:
    region:
      static: us-east-2
    stack:
      auto: false
    credentials:
      access-key: AKIAY3PLHSUJOAVAE24N
      secret-key: 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
loggin:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error